### ISSUE TITLE
Please retag/release for new composer.

### ISSUE THREAD

**Issue by rquadling** [gws/php-valueobjects#1]
Hi.

Really minor thing, but could you retag/release the lastest changes please?

Thank you.

**Comment by gws** [comment]
@rquadling I'd be happy to merge a PR, but I haven't worked in PHP for a while, so I'm not familiar with the new composer and am not sure what you're asking me to change. Would you be willing to submit a PR?

**Comment by rquadling** [comment]
I don't think tagging can be done via a PR.

Just tagging the latest master with a new v0.1.1.

**Comment by gws** [comment]
@rquadling Ah! Got it. I've tagged v0.1.1.

Thanks!

**Comment by rquadling** [comment]
Thank you!

**Comment by rquadling** [comment]
Another tag for latest version (drops PHP5.3, but adds PHP5.6).
