### ISSUE TITLE
gwis/php-valueobjects vs gws/php-valueobjects

### ISSUE THREAD

**Issue by rquadling** [gws/php-valueobjects#5]
Packagist is using https://packagist.org/packages/gwis/php-valueobjects
Github is using https://github.com/gws/php-valueobjects

The issue comes when I want to use my fork whilst waiting for a PR merge.

My composer has `
        {
            "type": "vcs",
            "url": "https://github.com/rquadling/php-valueobjects"
        },
` in the `repositories`, but the package name doesn't exist in both places.

I either have to say I want `gwis/php-valueobjects` when I am using Packagist (and therefore no fork) or `gws/php-valueobjects` when I am using Github (and therefore ONLY my fork which I'll delete once you've merged my PR).

Ideally they should be the same name.

Can this be resolved please?

**Comment by gws** [comment]
Yes, I didn't realize Packagist was using that old name. I've marked the `gwis` version abandoned and pointed folks toward the `gws` version.

Thanks!

**Comment by rquadling** [comment]
Thank you.
