### ISSUE TITLE
bcmath as a suggested extension.

### ISSUE THREAD

**Issue by rquadling** [gws/php-valueobjects#6]
For some reason, our production server wasn't built using `--enable-bcmath`. As a consequence we have to use `--ignore-platform-reqs` to get this package installed.

Is there any benefit in any of the following ideas:
1. Split php-valueobjects into more specific types.
2. Make any currently required extension a suggested extension and use extension sniffing to allow the class to be used (Money.php is currently the only user).

Having said that:
1. will still fail on production if locally bcmath is available, but fails at composer install stage.
2. will still fail on production if locally bcmath is available, but fails at runtime if the Money VO is used.

I suppose just getting the admin to install bcmath is the solution.

Unless you have any other ideas.

**Comment by gws** [comment]
There is definitely benefit in splitting the library up, but I don't use the library (or PHP) anymore, so I'll make the extensions `suggest`ed instead.

Fixed in b24f0e37847f43b85d3c4ae7b97c6fd7b5694a91.
