### ISSUE TITLE
Testing of date/datetime range anchors requires too much logic.

### ISSUE THREAD

**Issue by rquadling** [gws/php-valueobjects#8]
Currently, to test a DateRange (or DateTimeRange) to see if it is anchored in the PAST/FUTURE or both (INFINITE), you have to create a new `DateTime(DateRange::PAST)` or `DateTime(DateTimeRange::PAST)`.

https://github.com/gws/php-valueobjects/pull/7 allows you to simply test your existing range (date or datetime).

``` java
$dr1 = new DateRange(new DateTime('2006-09-06'), new DateTime('2006-09-15'));
$dr1->isPast(); // false
```

**Comment by gws** [comment]
Closed by #7. Thanks!
